### PR TITLE
Keep removal of markers in the caller's thread 

### PR DESCRIPTION
**Pull request by smithdtyler**
This change appears to avoid race conditions in creation/deletion of markers, specifically issue https://github.com/osate/osate2-core/issues/891

### CODE REVIEW

**Comment by lwrage** [comment]
Thanks! I'll see if this also fixes #613.

**Comment by philip-alldredge** [comment]
Why trying to track down a deadlock, I came across this as being involved. I'm looking into the cause on the graphical editor side. However, This change reintroduces issue #587. The commit log indicates the usage of a job was intended to fix that issue.

**Comment by smithdtyler** [comment]
This strikes me as an operating ordering problem. Is there something equivalent to Swing's Event Dispatch Thread for handling marker creation and destruction?

**Comment by philip-alldredge** [comment]
I believe the deadlock in the graphical editor has been fixed. As far as the problem with creating/deleting markers and #587.. There are mechanisms similar to Swing's event dispatch depending on whether it should be be performed in the main thread or using job mechanism but I don't know enough about the situation to comment on the proper behavior.

**Pull request merged**
