### PR TITLE
Fixed 831 by adding resource change listener to OsateCorePlugin

### LINKED ISSUE #831: Lost reference to renamed project
If one project is dependent on another.  If the project that is being dependent upon is renamed, the reference is lost.

### PR DESCRIPTION
**Pull request by AaronGreenhouse**
Fixed #831.  Tested as explained in #831.

### CODE REVIEW

**Comment by AaronGreenhouse** [comment]
I htought I did that already.  I'll check on it.

**Comment by AaronGreenhouse** [comment]
I was using Workspace.run() inside my Job, but I guess that isn't quiet the same thing.

**Comment by AaronGreenhouse** [comment]
My RenameJob in OsateCorePlugin uses Workspace.run() and a IWorkspaceRunnable internally.  Workspace.run() already batches all the change events, which is why I did this.

The WorkspaceModifyOperation is also based around using Workspace.run(), but is more geared towards UI-specific operatoins.  In particular, I don't have any way of actually running a WorkspaceModifyOperation, because my event handler odesn't have access to an IRunnableContext as would be available from insider a dialog box or wizard or some such thing like that.

**Comment by lwrage** [comment]
You can also just call `op.run(aMonitor)` to execute a `WorkspaceModifyOperation op`. This is what we do in class OsateText As you already take care of the batching, it wouldn't make a difference in functionality, but IMHO the code would be a little clearer.

**Comment by AaronGreenhouse** [comment]
But the WMO is still going to have to be in a separate job because it's being invoked by a resource listener that is already executing in the workspace.  I'm not sure that is going to make things any clearer.

It works the way it is now.

**Comment by lwrage** [comment]
Ah, my bad. I thought the WMO would create a job when it's run.

**Pull request merged**
